mysite/mapp/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'mapp'
urlpatterns = [
    path('', TemplateView.as_view(template_name='mapp/index.html')),
    path('mapp/out',
         views.MapCreateView.as_view(), name='map'),
    path('mapp/out2',
         views.MapCreateView2.as_view(), name='map2'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('mapp.urls')),
    path('admin/', admin.site.urls),
]

mysite/mapp/views.py
from django.shortcuts import render
from django.views import View
from django.views import generic
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
import cv2
import os
import re
import numpy as np
import json
import os
from imageai.Detection.Custom import CustomObjectDetection
import requests
import time


def get_image(lat, lon):
    detector = CustomObjectDetection()
    detector.setModelTypeAsYOLOv3()
    detector.setModelPath(
        "mapp/model/detection_model-ex-017--loss-0015.576.h5")
    detector.setJsonPath("mapp/config/detection_config.json")
    detector.loadModel()
    # print("hello")

    key = "YOUR_API_KEY"
    url = "https://maps.googleapis.com/maps/api/staticmap?"
    zoom = "18"
    size = "400x400"
    maptype = "satellite"
    scale = "4"

    time.sleep(5)
    center = str(lat) + "," + str(lon)
    # print(center)
    # center = "22.0748941,87.341307"
    uri = url+"center=" + center + "&zoom="+zoom+"&scale=" + \
        scale+"&size="+size+"&maptype="+maptype+"&key="+key
    r = requests.get(uri)
    img_file = "hello.png"
    f = open('mapp/image/'+img_file, 'wb')
    f.write(r.content)
    f.close()

    detections = detector.detectObjectsFromImage(
        input_image="mapp/image/hello.png", output_image_path="mapp/static/mapp/hello2.png", thread_safe=True)
    for detection in detections:
        print(detection["name"], " : ", detection["percentage_probability"],
              " : ", detection["box_points"])


class MapCreateView(View):
    def post(self, request):
        text = str(request.POST['map_create'])
        print(text)
        t1 = text.split(",")
        get_image(t1[0], t1[1])
        return render(request, 'mapp/output.html', {'message': text})

# Create your views here.


class MapCreateView2(View):
    def post(self, request):
        text1 = str(request.POST['latitude'])
        text2 = str(request.POST['longitude'])
        # text = 'Vishwas'
        # t1 = text.split(",")
        # get_image(t1[0], t1[1])
        get_image(text1, text2)
        return render(request, 'mapp/output.html')

mysite/mapp/templates/mapp/index.html
<!DOCTYPE html>
<html>

<head>
    <title>AFFORESTATION</title>

    <script
        src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap&libraries=&v=weekly"
        defer></script>

    <style type="text/css">
        h1 {
            text-align: center;
        }

        #map {
            height: 400px;
            /* The height is 400 pixels */
            width: 100%;
            /* The width is the width of the web page */
        }

        #myDIV {
            display: none;
        }

        /* Set the size of the div element that contains the map */
    </style>
    <script>
        // Initialize and add the map
        function initMap() {
            // The location of Uluru
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(successFunction);
            } else {
                alert('It seems like Geolocation, which is required for this page, is not enabled in your browser. Please use a browser which supports it.');
            }
            function successFunction(position) {
            x = position.coords.latitude ;
            y= position.coords.longitude;
            const uluru = { lat: x, lng: y};
            // The map, centered at Uluru
            const map = new google.maps.Map(document.getElementById("map"), {
                zoom: 18,
                center: uluru,
            });
            // The marker, positioned at Uluru
            const marker = new google.maps.Marker({
                position: uluru,
                map: map,
            });
        }}
    </script>
</head>

<body>
    <link rel="stylesheet" href="https://bootswatch.com/4/cerulean/bootstrap.min.css">
    <h1>AFFORESTATION APP</h1>
    <div id="map"></div>
    <div class="container">
        <script>
            function myFunction() {
                var x = document.getElementById("myDIV");
                if (x.style.display === "none") {
                    x.style.display = "block";
                } else {
                    x.style.display = "none";
                }
            }
        </script>
        <form name="mform" action="{% url 'mapp:map'%}" method="post">
            {% csrf_token %}
            <br><br>
            <button type="submit" name="map_create" value="1" class="btn btn-success">Current
                Location</button>
            <br><br>
        </form>
        <script>
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(successFunction);
            } else {
                alert('It seems like Geolocation, which is required for this page, is not enabled in your browser. Please use a browser which supports it.');
            }
            function successFunction(position) {
                test = position.coords.latitude + "," + position.coords.longitude;
                document.forms['mform']['map_create'].value = test;
            }
        </script>
        <button onclick="myFunction()" class="btn btn-success">Custom Input</button>
        <br><br>
        <div id="myDIV" class="form-group">
            <form action="{% url 'mapp:map2'%}" method="post">
                {% csrf_token %}
                <p>Latitude:</p>
                <input type="text" class="form-control" name="latitude" placeholder="Enter custom latitude">
                <br><br>
                <p>Longitude:</p>
                <input type="text" class="form-control" name="longitude" placeholder="Enter custom longitude">
                <br>
                <button type="submit" name="map_create2" class="btn btn-secondary">GO</button>
            </form>
        </div>

    </div>
</body>

</html>

mysite/mapp/templates/mapp/output.html
{% load static %}
<link rel="stylesheet" href="https://bootswatch.com/4/cerulean/bootstrap.min.css">
<style>
    .container {
        width: 75%;
        margin-left: auto;
        margin-right: auto;
        text-align: center;
    }
</style>
<div class="container">
    <br>
    <h1>🌴🌴Plantable Hotspots🎋🎋</h1>
    <br>
    <img src="{% static "mapp/hello2.png" %}" alt="MAP">
        <br><br>
        <a href="/" class="btn btn-primary">GO BACK</a>
        <!-- <button type="button" class="btn btn-primary">GO BACK</button> -->
</div>